name: CI/CD Pipeline

on: 
  push:
    branches:
      -  main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -  name: checkout-code
       uses: actions/checkout@v3

    -  name: create build directory
       run: |
            pwd
            mkdir build
            rsync -av --progress ./ ./build --exclude ./build
            zip -r build.zip build
            pwd
            


       
       
  
    
