name: CI/CD Pipeline

on: 
  push:
    branches:
      -  main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -  name: checkout-code
       uses: actions/checkout@v3

    -  name: create build directory
       run: |
            pwd
            ls -la
            mkdir build
            rsync -av --progress ./ ./build --exclude build
            pwd
            ls -R build
            zip -r build.zip build

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install CommandBox
        run: |
          curl -fsSl https://downloads.ortussolutions.com/debs/gpg | sudo apt-key add -
          echo "deb http://downloads.ortussolutions.com/debs/noarch /" | sudo tee -a /etc/apt/sources.list.d/commandbox.list
          sudo apt-get update && sudo apt-get install commandbox

      - name: Start ColdFusion Server
        run: box server start cfengine=lucee@5

      - name: Run Tests
        run: box testbox run


  sonarcloud:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
 
      - name: Verify Java Version
        run: java -version
    
      - name: Install SonarScanner
        run: |
          curl -sSLo sonar-scanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
          unzip sonar-scanner-cli.zip
          sudo mv sonar-scanner-4.8.0.2856-linux /usr/local/sonar-scanner
          sudo ln -s /usr/local/sonar-scanner/bin/sonar-scanner /usr/local/bin/sonar-scanner

      - name: Export JAVA_HOME for SonarScanner
        run: |
          export JAVA_HOME=/usr/lib/jvm/java-17-temurin
          export PATH=$JAVA_HOME/bin:$PATH
          echo "JAVA_HOME set to $JAVA_HOME"
          java -version

      - name: Run SonarCloud Analysis
        env:
          JAVA_HOME: /usr/lib/jvm/java-17-temurin
          PATH: /usr/lib/jvm/java-17-temurin/bin:$PATH
        run: |
          sonar-scanner \
            -Dsonar.projectKey=Cold_Fusion_Project \
            -Dsonar.organization=ilayarajac515 \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
  

        
          
 




    
            
            
            
            
       


       
       
  
    
