name: CI/CD Pipeline

on: 
  push:
    branches:
      -  main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -  name: checkout-code
       uses: actions/checkout@v3

    -  name: create build directory
       run: |
            pwd
            ls -la
            mkdir build
            rsync -av --progress ./ ./build --exclude build
            pwd
            ls -R build
            zip -r build.zip build

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install CommandBox
        run: |
          curl -fsSl https://downloads.ortussolutions.com/debs/gpg | sudo apt-key add -
          echo "deb http://downloads.ortussolutions.com/debs/noarch /" | sudo tee -a /etc/apt/sources.list.d/commandbox.list
          sudo apt-get update && sudo apt-get install commandbox

      - name: Start ColdFusion Server
        run: box server start cfengine=lucee@5

      - name: Run Tests
        run: box testbox run


  sonarcloud:
    runs-on: ubuntu-latest  # GitHub Actions default runner

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3  # Code fetch panna GitHub repository-la irundhu

      - name: Set up JDK 11  # SonarCloud-ku Java runtime thevai
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Run SonarCloud analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          # SonarScanner execute pannum commands
          npx sonar-scanner \
            -Dsonar.projectKey=Cold_Fusion_Project \
            -Dsonar.organization=ilayarajac515 \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN


        
          
 




    
            
            
            
            
       


       
       
  
    
