name: CI/CD Pipeline

on: 
  push:
    branches:
      -  main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -  name: checkout-code
       uses: actions/checkout@v3

    -  name: create build directory
       run: |
            pwd
            ls -la
            mkdir build
            rsync -av --progress ./ ./build --exclude build
            pwd
            ls -R build
            zip -r build.zip build


  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install CommandBox
        run: |
          curl -fsSL https://downloads.ortussolutions.com/ortus.key | sudo apt-key add -
          curl -fsSL https://www.ortussolutions.com/parent/download/commandbox/linux/64/latest | sudo bash

      - name: Start ColdFusion Server
        run: box server start cfengine=lucee@5

      - name: Run Tests
        run: box testbox run
 




    
            
            
            
            
       


       
       
  
    
