name: CI/CD Pipeline

on: 
  push:
    branches:
      -  main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -  name: checkout-code
       uses: actions/checkout@v3

    -  name: create build directory
       run: |
            pwd
            ls -la
            mkdir build
            rsync -av --progress ./ ./build --exclude build
            pwd
            ls -R build
            zip -r build.zip build


  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install CommandBox
        run: |
          curl -fsSl https://downloads.ortussolutions.com/debs/gpg | sudo apt-key add -
          echo "deb http://downloads.ortussolutions.com/debs/noarch /" | sudo tee -a /etc/apt/sources.list.d/commandbox.list
          sudo apt-get update && sudo apt-get install commandbox

      - name: Start ColdFusion Server
        run: box server start cfengine=lucee@5

      - name: Run Tests
        run: box testbox run


  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Install Trivy
        run: curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
      - name: Run Trivy Scan
        run: |
          pwd
          trivy fs .
          
 




    
            
            
            
            
       


       
       
  
    
