name: CI/CD Pipeline

on: 
  push:
    branches:
      -  main

jobs:
  check-out:
    runs-on: ubuntu-latest

    steps:
    -  name: checkout-code
       uses: actions/checkout@v3

  build:
    runs-on: ubuntu-latest

    steps:
    -  name: setup jdk
       uses: actions/setup-java@v3
       with:
         java-version: 11
         
    -  name: maven run
       run: mvn clean install

  test:
    runs-on: ubuntu-latest

    steps:
    -  name: test application
       run: mvn test
       
       
  
    
