name: CI/CD Pipeline

on: 
  push:
    branches:
      -  main
  workflow_dispatch:

jobs:
  check-out:
    runs-on: ubuntu-latest

    steps:
    -  name: checkout-code
       uses: actions/checkout@v3

  build:
    runs-on: ubuntu-latest

    steps: 
      -  name: create build directory
         run: |
            - name: Print Current Directory
              run: pwd
            - name: Create Build Directory
              run: mkdir build
            - name: Copy Files to Build Directory
              run: rsync -av --progress ./ ./build --exclude ./build
            - name: Zip Build Directory
              run: zip -r build.zip build
            - name: List Build Directory Content
              run: ls -R build


       
       
  
    
