name: CI/CD Pipeline

on: 
  push:
    branches:
      -  main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -  name: checkout-code
         uses: actions/checkout@v3

      -  name: Create Build Directory
         run: |
            mkdir build
            rsync -av --progress ./ ./build --exclude build
            zip -r build.zip build

      -  name: Verify Build.zip
         run: ls -la build.zip

      -  name: Build Docker Image
         run: |
            # Ensure build.zip is in the Docker build context
            mkdir docker-context
            mv build.zip docker-context/
            mv Dockerfile docker-context/
            docker build -t cold_fusion_app:latest ./docker-context

      -  name: Run Docker Container
         run: |
            docker run -d -p 8080:8080 --name cold_fusion_app_container cold_fusion_app:latest
