name: CI/CD Pipeline

on: 
  push:
    branches:
      -  main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -  name: checkout-code
         uses: actions/checkout@v3

      -  name: Create Build Directory
         run: |
            mkdir build
            rsync -av --progress ./ ./build --exclude build
            zip -r build.zip build

      -  name: Verify Build.zip
         run: ls -la build.zip

      -  name: Login to DockerHub
         run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      -  name: Build Docker Image
         run: |
            # Ensure build.zip is in the Docker build context
            mkdir docker-context
            mv build.zip docker-context/
            mv Dockerfile docker-context/
            docker build --no-cache -t cold_fusion_app:latest ./docker-context

      -  name: Verify Image Contents
         run: |
            docker run --entrypoint ls cold_fusion_app:latest -l /app

      -  name: Push Docker Image
         run: |
            docker tag cold_fusion_app:latest ${{ secrets.DOCKER_USERNAME }}/cold_fusion_app:latest
            docker push ${{ secrets.DOCKER_USERNAME }}/cold_fusion_app:latest

      # -  name: Run Docker Container
      #    run: |
      #       docker run -d -p 8080:8080 --name cold_fusion_app_container cold_fusion_app:latest
